=== ChezCoder/birb-tower-defense/dist/assets/game/schema/asset-directory.dtd
<!ELEMENT assets (asset*)>
<!ELEMENT asset (type,name,path,dims?)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT dims EMPTY>

<!ATTLIST assets type (content-asset) #REQUIRED>
<!ATTLIST dims width CDATA #REQUIRED><!ATTLIST dims height CDATA #REQUIRED>

=== ChezCoder/birb-tower-defense/dist/assets/game/directory.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE assets SYSTEM "./dtd/asset-directory.dtd">
<assets>
    <asset>
        <type>directory</type>
        <name>Image Assets Directory</name>
        <path>./images/directory.xml</path>
    </asset>
    <asset>
        <type>directory</type>
        <name>UI Assets Directory</name>
        <path>./ui/directory.xml</path>
    </asset>
    <asset>
        <type>directory</type>
        <name>Video Assets Directory</name>
        <path>./videos/directory.xml</path>
    </asset>
    <asset>
        <type>directory</type>
        <name>Audio Assets Directory</name>
        <path>./audios/directory.xml</path>
    </asset>
    <asset>
        <type>directory</type>
        <name>Definitions Directory</name>
        <path>./maps/directory.xml</path>
    </asset>
</assets>

=== ChezCoder/birb-tower-defense/dist/assets/game/audios/directory.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE assets SYSTEM "../schema/asset-directory.dtd">
<assets type="content-asset">
    <asset>
        <type>audio</type>
        <name>UI Hover</name>
        <path>./ui/hover.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Wow SFX</name>
        <path>./sfx/uwu-wow.mp3</path>
    </asset>



    
    <asset>
        <type>audio</type>
        <name>Menu Screen</name>
        <path>./bgm/sunny-days.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 1</name>
        <path>./bgm/jazz-01.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 2</name>
        <path>./bgm/jazz-02.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 3</name>
        <path>./bgm/jazz-03.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 4</name>
        <path>./bgm/jazz-04.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 5</name>
        <path>./bgm/jazz-05.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 6</name>
        <path>./bgm/jazz-06.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 7</name>
        <path>./bgm/jazz-07.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 8</name>
        <path>./bgm/jazz-08.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 9</name>
        <path>./bgm/jazz-09.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 10</name>
        <path>./bgm/jazz-10.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 11</name>
        <path>./bgm/jazz-11.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 12</name>
        <path>./bgm/jazz-12.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 13</name>
        <path>./bgm/jazz-13.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 14</name>
        <path>./bgm/jazz-14.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 15</name>
        <path>./bgm/jazz-15.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 16</name>
        <path>./bgm/jazz-16.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 17</name>
        <path>./bgm/jazz-17.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>Jazz 18</name>
        <path>./bgm/jazz-18.mp3</path>
    </asset>
    <asset>
        <type>audio</type>
        <name>VIBE</name>
        <path>./thenewsweetgroove.mp3</path>
    </asset>
</assets>

=== ChezCoder/birb-tower-defense/dist/assets/game/images/directory.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE assets SYSTEM "../schema/asset-directory.dtd">
<assets type="content-asset">
    <asset>
        <type>image</type>
        <name>Neutral Tile 1</name>
        <path>neutral-tile-1.svg</path>
        <dims width="128" height="128"/>
    </asset>
    <asset>
        <type>image</type>
        <name>Neutral Tile 2</name>
        <path>neutral-tile-2.svg</path>
        <dims width="128" height="128"/>
    </asset>
    <asset>
        <type>image</type>
        <name>Neutral Tile 3</name>
        <path>neutral-tile-3.svg</path>
        <dims width="128" height="128"/>
    </asset>
    <asset>
        <type>image</type>
        <name>Neutral Tile 4</name>
        <path>neutral-tile-4.svg</path>
        <dims width="128" height="128"/>
    </asset>
    <asset>
        <type>image</type>
        <name>Neutral Tile 5</name>
        <path>neutral-tile-5.svg</path>
        <dims width="128" height="128"/>
    </asset>
    <asset>
        <type>image</type>
        <name>Neutral Tile 6</name>
        <path>neutral-tile-6.svg</path>
        <dims width="128" height="128"/>
    </asset>
</assets>

=== ChezCoder/birb-tower-defense/dist/assets/game/entities/directory.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE assets SYSTEM "../schema/asset-directory.dtd">
<assets type="content-asset">
    <asset>
        <type>image</type>
        <name>Null Egg</name>
        <path>./null_egg.svg</path>
    </asset>
    <asset>
        <type>image</type>
        <name>Sparrow Egg</name>
        <path>./sparrow_egg.svg</path>
    </asset>
    <asset>
        <type>image</type>
        <name>Bluebird Egg</name>
        <path>./bluebird_egg.svg</path>
    </asset>
    <asset>
        <type>image</type>
        <name>Blackbird Egg</name>
        <path>./blackbird_egg.svg</path>
    </asset>
    <asset>
        <type>image</type>
        <name>Quail Egg</name>
        <path>./quail_egg.svg</path>
    </asset>
</assets>
