=== ChezCoder/birb-tower-defense/dist/assets/game/schema/data-directory.dtd
<!ELEMENT assets (data*)>
<!ELEMENT data (type,name,path)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT path (#PCDATA)>

<!ATTLIST assets type (data-asset) #REQUIRED>

=== ChezCoder/birb-tower-defense/dist/assets/game/data/directory.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE assets SYSTEM "../schema/data-directory.dtd">
<assets type="data-asset">
    <data>
        <type>map</type>
        <name>Game://Beta</name>
        <path>./maps/game-beta.json</path>
    </data>

    <data>
        <type>mode</type>
        <name>Standard</name>
        <path>./modes/standard.json</path>
    </data>
</assets>
